---
# tasks file for paultaiton.vscode
- name: microsoft rpm key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Yum repo definitions
  copy:
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: 0644
    src: "{{ item }}.repo"
  loop:
    - vscode

- name: add extra packages
  dnf:
    name:
     - code
    state: latest

